name: Cypress Test Runner
"on":
  push:
    branches: 
      - main
jobs: 
  cypress_test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          yarn install

      - name: Cypress Run
        uses: cypress-io/github-action@v2
        with:
          start: yarn dev
          config-file: cypress-config.ts
          wait-on: "http://localhost:3000"
          wait-on-timeout: 300
          browser: chrome
          headless: true